db.createCollection("SACH", {
  capped: false,
  validator: {
    $jsonSchema: {
      bsonType: "object",
      title: "SACH",
      properties: {
        _id: {
          bsonType: "objectId",
        },
        maSach: {
          bsonType: "string",
        },
        tenSach: {
          bsonType: "string",
        },
        theLoai: {
          bsonType: "string",
        },
        gioiThieu: {
          bsonType: "string",
        },
        donGia: {
          bsonType: "number",
        },
        soLuong: {
          bsonType: "number",
        },
        conLai: {
          bsonType: "number",
        },
        namXuatBan: {
          bsonType: "date",
        },
        TacGia: {
          bsonType: "string",
        },
        dichGia: {
          bsonType: "string",
        },
        maNXB: {
          bsonType: "string",
        },
        danhGia: {
          bsonType: "number",
        },
      },
      additionalProperties: false,
    },
  },
  validationLevel: "off",
  validationAction: "warn",
});

db.SACH.insertMany([
  // NXB Trẻ (NXB001) - 10 books
  {
    maSach: "S001",
    tenSach: "Cho tôi xin một vé đi tuổi thơ",
    theLoai: "Văn học",
    gioiThieu:
      "Một tác phẩm kinh điển của Nguyễn Nhật Ánh, đưa độc giả trở về thế giới tuổi thơ trong trẻo và đầy ắp kỷ niệm. Câu chuyện xoay quanh cu Mùi và những người bạn thân thiết ở một làng quê yên bình. Tác phẩm không chỉ là những trò chơi tinh nghịch, những rung động đầu đời, mà còn là những suy ngẫm sâu sắc về tình bạn, gia đình và sự trôi chảy của thời gian. Với giọng văn hóm hỉnh và gần gũi, cuốn sách là một tấm vé quý giá cho bất kỳ ai muốn tìm lại một phần ký ức đã mất.",
    donGia: 85000,
    soLuong: 20,
    conLai: 15,
    namXuatBan: "2023",
    TacGia: "Nguyễn Nhật Ánh",
    dichGia: "",
    maNXB: "NXB001",
  },
  {
    maSach: "S002",
    tenSach: "Cánh đồng bất tận",
    theLoai: "Truyện ngắn",
    gioiThieu:
      "Tập truyện ngắn nổi tiếng của Nguyễn Ngọc Tư, vẽ nên một bức tranh chân thực và đầy ám ảnh về cuộc sống của những con người lênh đênh trên sông nước miền Tây. Mỗi câu chuyện là một mảnh đời, một số phận với những nỗi đau, sự mất mát nhưng vẫn le lói tình yêu thương và khát vọng sống. Ngôn từ mộc mạc, giàu hình ảnh và đậm chất Nam Bộ của tác giả đã chạm đến trái tim của hàng triệu độc giả.",
    donGia: 95000,
    soLuong: 10,
    conLai: 8,
    namXuatBan: "2022",
    TacGia: "Nguyễn Ngọc Tư",
    dichGia: "",
    maNXB: "NXB001",
  },
  // ... adding more variety for NXB Trẻ
  {
    maSach: "S003",
    tenSach: "Harry Potter và Hòn đá Phù thủy",
    theLoai: "Fantasy",
    gioiThieu:
      "Mở đầu cho series huyền thoại, cuốn sách giới thiệu về Harry Potter, cậu bé mồ côi bất ngờ phát hiện ra mình là một phù thủy. Độc giả sẽ cùng Harry bước vào cuộc phiêu lưu kỳ thú tại Trường Phù thủy và Pháp sư Hogwarts, nơi cậu kết bạn với Ron và Hermione, học những phép thuật kỳ diệu và đối mặt với Chúa tể Hắc ám Voldemort. Đây là một thế giới đầy mê hoặc về tình bạn, lòng dũng cảm và cuộc chiến giữa cái thiện và cái ác.",
    donGia: 150000,
    soLuong: 30,
    conLai: 12,
    namXuatBan: "2021",
    TacGia: "J.K. Rowling",
    dichGia: "Lý Lan",
    maNXB: "NXB001",
  },
  {
    maSach: "S004",
    tenSach: "Mắt biếc",
    theLoai: "Lãng mạn",
    gioiThieu:
      "Một trong những tác phẩm lãng mạn và day dứt nhất của Nguyễn Nhật Ánh. Truyện kể về mối tình đơn phương của Ngạn dành cho Hà Lan, cô bạn có đôi mắt biếc tuyệt đẹp. Tình yêu của Ngạn thủy chung, son sắt qua bao năm tháng, dù Hà Lan chạy theo những cám dỗ của thành thị và trải qua nhiều biến cố. 'Mắt biếc' là một bản tình ca buồn về sự chờ đợi, hy sinh và vẻ đẹp của một tình yêu không bao giờ phai nhạt.",
    donGia: 110000,
    soLuong: 15,
    conLai: 5,
    namXuatBan: "2020",
    TacGia: "Nguyễn Nhật Ánh",
    dichGia: "",
    maNXB: "NXB001",
  },
  {
    maSach: "S005",
    tenSach: "Dế Mèn Phiêu Lưu Ký",
    theLoai: "Thiếu nhi",
    gioiThieu:
      "Tác phẩm văn học thiếu nhi kinh điển của Tô Hoài, kể về hành trình phiêu lưu của chú Dế Mèn cường tráng nhưng kiêu ngạo. Từ một bài học đau lòng do sự ngông cuồng của mình, Dế Mèn đã bắt đầu một cuộc chu du thiên hạ, kết giao bằng hữu và học được nhiều bài học quý giá về lòng dũng cảm, sự khiêm tốn và tình bạn. Cuốn sách là một thế giới côn trùng sống động và đầy màu sắc.",
    donGia: 45000,
    soLuong: 50,
    conLai: 40,
    namXuatBan: "2024",
    TacGia: "Tô Hoài",
    dichGia: "",
    maNXB: "NXB001",
  },
  {
    maSach: "S006",
    tenSach: "Bàn có năm chỗ ngồi",
    theLoai: "Thiếu nhi",
    gioiThieu:
      "Câu chuyện ấm áp và cảm động về tình bạn của một nhóm học sinh đặc biệt. Bốn người bạn thân thiết đã cùng nhau chào đón một thành viên mới, một cô bé mồ côi, vào chiếc bàn học của mình. Tác phẩm ca ngợi vẻ đẹp của tình bạn trong sáng, sự sẻ chia, và lòng bao dung, cho thấy rằng tình bạn có thể sưởi ấm những tâm hồn cô đơn nhất.",
    donGia: 60000,
    soLuong: 10,
    conLai: 10,
    namXuatBan: "2022",
    TacGia: "Nguyễn Nhật Ánh",
    dichGia: "",
    maNXB: "NXB001",
  },
  {
    maSach: "S007",
    tenSach: "Tôi là Bêtô",
    theLoai: "Văn học",
    gioiThieu:
      "Một cuốn sách độc đáo được kể qua góc nhìn của một chú chó tên Bêtô. Độc giả sẽ được khám phá thế giới loài người qua những suy ngẫm ngộ nghĩnh, triết lý và đầy yêu thương của Bêtô về cô chủ Ni, về cuộc sống và về tình bạn giữa các loài vật. Tác phẩm là một lời nhắc nhở nhẹ nhàng về tình yêu thương và sự gắn kết giữa con người và vật nuôi.",
    donGia: 75000,
    soLuong: 12,
    conLai: 9,
    namXuatBan: "2023",
    TacGia: "Nguyễn Nhật Ánh",
    dichGia: "",
    maNXB: "NXB001",
  },
  {
    maSach: "S008",
    tenSach: "Ngồi khóc trên cây",
    theLoai: "Lãng mạn",
    gioiThieu:
      "Câu chuyện tình yêu trong sáng và lãng mạn giữa Rùa, một cô bé mồ côi sống giữa thiên nhiên, và một chàng sinh viên thành thị. Mối tình của họ nảy nở giữa khung cảnh làng quê thơ mộng, với những cảm xúc đầu đời ngây ngô và mãnh liệt. Tác phẩm là một khúc ca về tình yêu, thiên nhiên và những giá trị bình dị của cuộc sống.",
    donGia: 99000,
    soLuong: 8,
    conLai: 2,
    namXuatBan: "2021",
    TacGia: "Nguyễn Nhật Ánh",
    dichGia: "",
    maNXB: "NXB001",
  },
  {
    maSach: "S009",
    tenSach: "Đảo mộng mơ",
    theLoai: "Thiếu nhi",
    gioiThieu:
      "Cuộc phiêu lưu thú vị của một nhóm trẻ em thành phố khi chúng bị lạc trên một hòn đảo hoang. Tại đây, chúng phải học cách sinh tồn, đoàn kết và xây dựng một xã hội thu nhỏ của riêng mình. 'Đảo mộng mơ' là một câu chuyện hấp dẫn về trí tưởng tượng, sự tự lập và sức mạnh của tình bạn khi đối mặt với thử thách.",
    donGia: 82000,
    soLuong: 15,
    conLai: 14,
    namXuatBan: "2022",
    TacGia: "Nguyễn Nhật Ánh",
    dichGia: "",
    maNXB: "NXB001",
  },
  {
    maSach: "S010",
    tenSach: "Lá nằm trong lá",
    theLoai: "Văn học",
    gioiThieu:
      "Tuyển tập những câu chuyện nhỏ, những tản văn nhẹ nhàng và tinh tế của Nguyễn Nhật Ánh. Mỗi trang sách là một lát cắt của cuộc sống, từ những kỷ niệm tuổi thơ, những rung động đầu đời cho đến những suy ngẫm về tình yêu và lẽ sống. Giọng văn trong trẻo, giàu chất thơ của tác giả sẽ mang đến cho độc giả những giây phút bình yên và sâu lắng.",
    donGia: 88000,
    soLuong: 10,
    conLai: 7,
    namXuatBan: "2023",
    TacGia: "Nguyễn Nhật Ánh",
    dichGia: "",
    maNXB: "NXB001",
  },

  // NXB Kim Đồng (NXB002) - 10 books (Manga & Kids)
  {
    maSach: "S011",
    tenSach: "Doraemon Vol 1",
    theLoai: "Manga",
    gioiThieu:
      "Bộ truyện tranh kinh điển đã gắn liền với tuổi thơ của nhiều thế hệ. Câu chuyện bắt đầu khi chú mèo máy Doraemon đến từ thế kỷ 22 để giúp đỡ cậu bé Nobita hậu đậu và yếu đuối. Với chiếc túi thần kỳ chứa đầy những bảo bối tương lai, Doraemon đã mang đến cho Nobita và bạn bè những cuộc phiêu lưu không thể nào quên, cùng những bài học ý nghĩa về tình bạn, lòng dũng cảm và sự nỗ lực.",
    donGia: 25000,
    soLuong: 100,
    conLai: 80,
    namXuatBan: "2024",
    TacGia: "Fujiko F. Fujio",
    dichGia: "NXB Kim Đồng",
    maNXB: "NXB002",
  },
  {
    maSach: "S012",
    tenSach: "Conan Vol 100",
    theLoai: "Manga",
    gioiThieu:
      "Thám tử lừng danh Shinichi Kudo bị một tổ chức áo đen bí ẩn ép uống thuốc độc và bị teo nhỏ thành một cậu bé tiểu học. Lấy tên là Edogawa Conan, cậu tiếp tục phá những vụ án hóc búa trong khi tìm kiếm tung tích của tổ chức áo đen. Bộ truyện là sự kết hợp hấp dẫn giữa yếu tố trinh thám, hành động và hài hước, với những vụ án thông minh và những nhân vật được yêu thích.",
    donGia: 30000,
    soLuong: 50,
    conLai: 20,
    namXuatBan: "2023",
    TacGia: "Gosho Aoyama",
    dichGia: "Nguyễn Phương",
    maNXB: "NXB002",
  },
  {
    maSach: "S013",
    tenSach: "One Piece Vol 1",
    theLoai: "Manga",
    gioiThieu:
      "Bắt đầu cuộc hành trình vĩ đại của Monkey D. Luffy, một cậu bé có khả năng co giãn cơ thể sau khi ăn phải trái ác quỷ. Với ước mơ trở thành Vua Hải Tặc, Luffy đã ra khơi và tập hợp những người bạn đồng hành để cùng nhau tìm kiếm kho báu huyền thoại One Piece. 'One Piece' là một thế giới rộng lớn đầy phiêu lưu, hài hước, và những trận chiến hoành tráng, ca ngợi sức mạnh của tình bạn và ước mơ.",
    donGia: 25000,
    soLuong: 60,
    conLai: 55,
    namXuatBan: "2024",
    TacGia: "Eiichiro Oda",
    dichGia: "NXB Kim Đồng",
    maNXB: "NXB002",
  },
  {
    maSach: "S014",
    tenSach: "Naruto Vol 1",
    theLoai: "Manga",
    gioiThieu:
      "Câu chuyện kể về Naruto Uzumaki, một ninja trẻ mồ côi, ồn ào và luôn tìm cách gây chú ý. Bị xa lánh vì mang trong mình Cửu Vĩ Hồ Ly, Naruto vẫn không từ bỏ ước mơ trở thành Hokage - người lãnh đạo làng Lá. Bộ truyện là hành trình trưởng thành của Naruto, nơi cậu học được giá trị của tình bạn, sự kiên trì và lòng vị tha qua những trận chiến và thử thách khắc nghiệt.",
    donGia: 25000,
    soLuong: 40,
    conLai: 38,
    namXuatBan: "2023",
    TacGia: "Masashi Kishimoto",
    dichGia: "NXB Kim Đồng",
    maNXB: "NXB002",
  },
  {
    maSach: "S015",
    tenSach: "Dragon Ball Vol 1",
    theLoai: "Manga",
    gioiThieu:
      "Huyền thoại manga bắt đầu với cuộc gặp gỡ giữa cậu bé có đuôi khỉ Son Goku và cô gái thông minh Bulma. Cả hai cùng nhau lên đường tìm kiếm bảy viên ngọc rồng, những viên ngọc có khả năng triệu hồi một con rồng thần ban điều ước. Trên hành trình đó, họ đã gặp gỡ nhiều bạn bè, đối đầu với những kẻ thù hùng mạnh và tham gia vào những đại hội võ thuật kịch tính.",
    donGia: 25000,
    soLuong: 70,
    conLai: 65,
    namXuatBan: "2024",
    TacGia: "Akira Toriyama",
    dichGia: "NXB Kim Đồng",
    maNXB: "NXB002",
  },
  {
    maSach: "S016",
    tenSach: "Shin - Cậu bé bút chì",
    theLoai: "Manga",
    gioiThieu:
      "Những câu chuyện hài hước xoay quanh cuộc sống hàng ngày của cậu bé 5 tuổi Shinnosuke Nohara, hay còn gọi là Shin. Với tính cách tinh nghịch, những phát ngôn ngô nghê và những hành động không giống ai, Shin đã gây ra vô số tình huống dở khóc dở cười cho gia đình, bạn bè và thầy cô. Bộ truyện mang lại tiếng cười sảng khoái và cái nhìn hài hước về thế giới trẻ thơ.",
    donGia: 20000,
    soLuong: 100,
    conLai: 90,
    namXuatBan: "2024",
    TacGia: "Yoshito Usui",
    dichGia: "NXB Kim Đồng",
    maNXB: "NXB002",
  },
  {
    maSach: "S017",
    tenSach: "Kính vạn hoa",
    theLoai: "Thiếu nhi",
    gioiThieu:
      "Bộ truyện dài tập nổi tiếng của Nguyễn Nhật Ánh, kể về những cuộc phiêu lưu và phá án của bộ ba Quý ròm, nhỏ Hạnh và Tiểu Long. Mỗi tập là một vụ việc ly kỳ, từ những chuyện nhỏ nhặt trong trường học đến những bí ẩn lớn hơn. 'Kính vạn hoa' không chỉ hấp dẫn bởi yếu tố trinh thám mà còn mang đậm giá trị giáo dục về tình bạn, lòng trung thực và sự dũng cảm.",
    donGia: 55000,
    soLuong: 20,
    conLai: 18,
    namXuatBan: "2022",
    TacGia: "Nguyễn Nhật Ánh",
    dichGia: "",
    maNXB: "NXB002",
  },
  {
    maSach: "S018",
    tenSach: "Cơ thể người",
    theLoai: "Khoa học",
    gioiThieu:
      "Một cuốn sách kiến thức bổ ích, giúp độc giả trẻ khám phá những điều kỳ diệu và phức tạp của cơ thể con người. Với hình ảnh minh họa sinh động và lời giải thích dễ hiểu, sách giới thiệu về các hệ cơ quan, chức năng của chúng và cách để giữ gìn một cơ thể khỏe mạnh. Đây là một cẩm nang khoa học hấp dẫn cho những ai tò mò về chính bản thân mình.",
    donGia: 120000,
    soLuong: 10,
    conLai: 5,
    namXuatBan: "2023",
    TacGia: "Nhiều tác giả",
    dichGia: "Minh Anh",
    maNXB: "NXB002",
  },
  {
    maSach: "S019",
    tenSach: "Lịch sử Việt Nam",
    theLoai: "Lịch sử",
    gioiThieu:
      "Cuốn sách cung cấp một cái nhìn tổng quan, súc tích về lịch sử hàng ngàn năm của dân tộc Việt Nam, từ thời kỳ Hùng Vương dựng nước cho đến ngày nay. Sách trình bày các sự kiện, nhân vật và các triều đại quan trọng một cách hệ thống, giúp độc giả, đặc biệt là các bạn trẻ, hiểu rõ hơn về cội nguồn và quá trình đấu tranh dựng nước, giữ nước hào hùng của cha ông.",
    donGia: 95000,
    soLuong: 15,
    conLai: 12,
    namXuatBan: "2024",
    TacGia: "Nhiều tác giả",
    dichGia: "",
    maNXB: "NXB002",
  },
  {
    maSach: "S020",
    tenSach: "Thần thoại Hy Lạp",
    theLoai: "Văn học",
    gioiThieu:
      "Tuyển tập những câu chuyện hấp dẫn và đầy màu sắc về thế giới của các vị thần trên đỉnh Olympus, các anh hùng dũng mãnh và những quái vật đáng sợ trong thần thoại Hy Lạp. Độc giả sẽ được gặp gỡ thần Zeus, Hercules, Achilles... và khám phá những câu chuyện giải thích về nguồn gốc thế giới, các hiện tượng tự nhiên và bản chất con người. Đây là nền tảng của văn minh phương Tây và là nguồn cảm hứng bất tận cho nghệ thuật.",
    donGia: 110000,
    soLuong: 10,
    conLai: 8,
    namXuatBan: "2023",
    TacGia: "Nhiều tác giả",
    dichGia: "Hữu Ngọc",
    maNXB: "NXB002",
  },

  // Nhã Nam (NXB003) - 10 books (Literature & Philosophy)
  {
    maSach: "S021",
    tenSach: "Nhà Giả Kim",
    theLoai: "Tiểu thuyết",
    gioiThieu:
      "Tác phẩm kinh điển của Paulo Coelho, kể về hành trình của chàng chăn cừu Santiago từ Tây Ban Nha đến Ai Cập để tìm kiếm kho báu. Cuốn sách không chỉ là một cuộc phiêu lưu vật chất, mà còn là một hành trình tâm linh sâu sắc để khám phá 'vận mệnh của bản thân'. Với ngôn ngữ giản dị và đầy chất thơ, 'Nhà Giả Kim' đã truyền cảm hứng cho hàng triệu người trên thế giới đi theo tiếng gọi của trái tim mình.",
    donGia: 79000,
    soLuong: 40,
    conLai: 35,
    namXuatBan: "2023",
    TacGia: "Paulo Coelho",
    dichGia: "Lê Chu Cầu",
    maNXB: "NXB003",
  },
  {
    maSach: "S022",
    tenSach: "Hoàng tử bé",
    theLoai: "Văn học",
    gioiThieu:
      "Một kiệt tác văn học của Antoine de Saint-Exupéry, được yêu thích bởi cả trẻ em và người lớn. Câu chuyện kể về cuộc gặp gỡ giữa một phi công bị rơi máy bay trên sa mạc và một hoàng tử bé đến từ một hành tinh xa xôi. Qua những cuộc trò chuyện và hành trình của hoàng tử bé, tác phẩm đặt ra những câu hỏi triết lý sâu sắc về tình bạn, tình yêu, sự mất mát và ý nghĩa thực sự của cuộc sống.",
    donGia: 65000,
    soLuong: 25,
    conLai: 20,
    namXuatBan: "2024",
    TacGia: "Antoine de Saint-Exupéry",
    dichGia: "Vĩnh Lạc",
    maNXB: "NXB003",
  },
  {
    maSach: "S023",
    tenSach: "Suối Nguồn",
    theLoai: "Kinh điển",
    gioiThieu:
      "Một tiểu thuyết đồ sộ và đầy tham vọng của Ayn Rand, là tuyên ngôn của chủ nghĩa khách quan. Tác phẩm xoay quanh cuộc đấu tranh của Howard Roark, một kiến trúc sư thiên tài, người từ chối thỏa hiệp với những tiêu chuẩn nghệ thuật truyền thống và định kiến xã hội. 'Suối Nguồn' là một bài ca hùng tráng về chủ nghĩa cá nhân, sự sáng tạo và sức mạnh của ý chí con người.",
    donGia: 250000,
    soLuong: 10,
    conLai: 4,
    namXuatBan: "2022",
    TacGia: "Ayn Rand",
    dichGia: "Vũ Hải Đăng",
    maNXB: "NXB003",
  },
  {
    maSach: "S024",
    tenSach: "Rừng Na Uy",
    theLoai: "Tiểu thuyết",
    gioiThieu:
      "Tác phẩm đã đưa tên tuổi Haruki Murakami ra toàn thế giới. Lấy bối cảnh Nhật Bản những năm 1960, truyện là lời hồi tưởng của Toru Watanabe về tuổi trẻ của mình, về những mối tình với hai người con gái đặc biệt: Naoko mong manh và Midori cá tính. 'Rừng Na Uy' là một câu chuyện buồn và đẹp về tình yêu, sự mất mát, nỗi cô đơn và hành trình đi tìm bản ngã của những người trẻ tuổi.",
    donGia: 140000,
    soLuong: 15,
    conLai: 10,
    namXuatBan: "2023",
    TacGia: "Haruki Murakami",
    dichGia: "Trịnh Lữ",
    maNXB: "NXB003",
  },
  {
    maSach: "S025",
    tenSach: "Khởi hành",
    theLoai: "Tâm lý",
    gioiThieu:
      "Cuốn hồi ký đầy cảm hứng của Tara Westover, kể về hành trình phi thường của cô từ một cô gái lớn lên trong một gia đình cuồng tín ở Idaho, chưa bao giờ đến trường, cho đến khi trở thành tiến sĩ tại Đại học Cambridge. 'Khởi hành' là một câu chuyện mạnh mẽ về sức mạnh của giáo dục, về sự giằng xé giữa tình yêu gia đình và khát vọng tìm kiếm tri thức và bản sắc cá nhân.",
    donGia: 125000,
    soLuong: 20,
    conLai: 15,
    namXuatBan: "2023",
    TacGia: "Bill Gates",
    dichGia: "Minh Quang",
    maNXB: "NXB003",
  },
  {
    maSach: "S026",
    tenSach: "Lược sử thời gian",
    theLoai: "Khoa học",
    gioiThieu:
      "Một trong những cuốn sách khoa học phổ thông bán chạy nhất mọi thời đại. Nhà vật lý thiên tài Stephen Hawking đã giải thích những khái niệm phức tạp nhất của vũ trụ học - từ Vụ Nổ Lớn, lỗ đen cho đến bản chất của thời gian - bằng một ngôn ngữ sáng sủa và dễ tiếp cận. Cuốn sách mở ra một cánh cửa để độc giả đại chúng có thể chiêm ngưỡng vẻ đẹp và sự kỳ diệu của vũ trụ.",
    donGia: 165000,
    soLuong: 12,
    conLai: 11,
    namXuatBan: "2022",
    TacGia: "Stephen Hawking",
    dichGia: "Cao Chi",
    maNXB: "NXB003",
  },
  {
    maSach: "S027",
    tenSach: "1984",
    theLoai: "Kinh điển",
    gioiThieu:
      "Một tiểu thuyết phản địa đàng kinh điển của George Orwell, vẽ nên một bức tranh đáng sợ về một xã hội toàn trị trong tương lai, nơi Đảng kiểm soát mọi khía cạnh của cuộc sống, từ hành động đến suy nghĩ. Nhân vật chính, Winston Smith, đã cố gắng nổi dậy chống lại sự áp bức của 'Anh Cả'. Tác phẩm là một lời cảnh báo sâu sắc về sự nguy hiểm của chủ nghĩa độc tài và tầm quan trọng của tự do cá nhân.",
    donGia: 115000,
    soLuong: 10,
    conLai: 9,
    namXuatBan: "2024",
    TacGia: "George Orwell",
    dichGia: "Phạm Nguyên Tùng",
    maNXB: "NXB003",
  },
  {
    maSach: "S028",
    tenSach: "Bắt trẻ đồng xanh",
    theLoai: "Văn học",
    gioiThieu:
      "Tác phẩm kinh điển của J.D. Salinger, kể về vài ngày trong cuộc đời của Holden Caulfield, một thiếu niên 16 tuổi vừa bị đuổi học. Lang thang ở New York, Holden phải đối mặt với sự giả tạo của thế giới người lớn và cảm giác cô đơn, lạc lõng của tuổi mới lớn. Cuốn sách đã trở thành tiếng nói của nhiều thế hệ thanh thiếu niên cảm thấy nổi loạn và xa lạ với xã hội.",
    donGia: 85000,
    soLuong: 20,
    conLai: 19,
    namXuatBan: "2023",
    TacGia: "J.D. Salinger",
    dichGia: "Phùng Khánh",
    maNXB: "NXB003",
  },
  {
    maSach: "S029",
    tenSach: "Giết con chim nhạn",
    theLoai: "Kinh điển",
    gioiThieu:
      "Một kiệt tác của văn học Mỹ, được kể qua con mắt của cô bé Scout Finch. Cha cô, luật sư Atticus Finch, đã dũng cảm bảo vệ một người đàn ông da đen bị buộc tội oan. Tác phẩm không chỉ là một câu chuyện cảm động về tình cha con, mà còn là một bản cáo trạng mạnh mẽ về nạn phân biệt chủng tộc, sự bất công và lòng dũng cảm đứng lên bảo vệ lẽ phải ở miền Nam nước Mỹ.",
    donGia: 135000,
    soLuong: 15,
    conLai: 13,
    namXuatBan: "2022",
    TacGia: "Harper Lee",
    dichGia: "Huỳnh Kim Oanh",
    maNXB: "NXB003",
  },
  {
    maSach: "S030",
    tenSach: "Trăm năm cô đơn",
    theLoai: "Kinh điển",
    gioiThieu:
      "Một đỉnh cao của chủ nghĩa hiện thực huyền ảo, kể về lịch sử của dòng họ Buendía qua bảy thế hệ tại ngôi làng Macondo hư cấu. Gabriel García Márquez đã dệt nên một câu chuyện kỳ vĩ về tình yêu, chiến tranh, sự cô đơn và vòng lặp của số phận. Tác phẩm là một bức tranh hoành tráng và đầy mê hoặc về lịch sử và văn hóa của châu Mỹ Latinh.",
    donGia: 190000,
    soLuong: 8,
    conLai: 5,
    namXuatBan: "2021",
    TacGia: "Gabriel García Márquez",
    dichGia: "Nguyễn Trung Đức",
    maNXB: "NXB003",
  },

  // (Remaining 20 books for NXB004 and NXB005 follow the same pattern...)
  // ... adding more titles to reach 50 ...
]);

db.SACH.insertMany([
  // NXB Tổng hợp TP.HCM (NXB004) - 10 cuốn (Lịch sử, Kinh tế, Văn hóa)
  {
    maSach: "S031",
    tenSach: "Gia Định Thành Thông Chí",
    theLoai: "Lịch sử",
    gioiThieu:
      "Một công trình địa chí vô giá của học giả Trịnh Hoài Đức, ghi chép một cách chi tiết và toàn diện về địa lý, lịch sử, kinh tế, và văn hóa của vùng đất Gia Định (Nam Bộ) vào đầu thế kỷ 19. Đây là một nguồn tư liệu gốc quan trọng cho bất kỳ ai muốn nghiên cứu về lịch sử và văn hóa của miền Nam Việt Nam.",
    donGia: 180000,
    soLuong: 10,
    conLai: 8,
    namXuatBan: "2022",
    TacGia: "Trịnh Hoài Đức",
    dichGia: "",
    maNXB: "NXB004",
  },
  {
    maSach: "S032",
    tenSach: "Sài Gòn Chuyện Đời Của Phố",
    theLoai: "Tản văn",
    gioiThieu:
      "Tập tản văn của Phạm Công Luận đưa độc giả vào một hành trình đầy hoài niệm về Sài Gòn xưa. Qua những câu chuyện về con người, những góc phố, những món ăn và những nếp sống cũ, một Sài Gòn hào hoa, phóng khoáng và đầy tình người hiện lên sống động. Cuốn sách dành cho những ai yêu mến và muốn tìm hiểu về tâm hồn của thành phố này.",
    donGia: 120000,
    soLuong: 15,
    conLai: 12,
    namXuatBan: "2023",
    TacGia: "Phạm Công Luận",
    dichGia: "",
    maNXB: "NXB004",
  },
  {
    maSach: "S033",
    tenSach: "Kinh tế học cơ bản",
    theLoai: "Kinh tế",
    gioiThieu:
      "Nhà kinh tế học Thomas Sowell đã thành công trong việc giải thích những nguyên lý kinh tế phức tạp bằng một ngôn ngữ đơn giản, không cần đến biểu đồ hay thuật ngữ chuyên ngành. Cuốn sách giúp độc giả hiểu được cách nền kinh tế vận hành trong thực tế, từ giá cả, tiền lương cho đến thương mại quốc tế. Đây là cuốn sách vỡ lòng tuyệt vời cho bất kỳ ai muốn tìm hiểu về kinh tế học.",
    donGia: 210000,
    soLuong: 20,
    conLai: 15,
    namXuatBan: "2024",
    TacGia: "Thomas Sowell",
    dichGia: "Trần Quân",
    maNXB: "NXB004",
  },
  {
    maSach: "S034",
    tenSach: "Vùng đất Nam Bộ",
    theLoai: "Nghiên cứu",
    gioiThieu:
      "Công trình nghiên cứu đồ sộ của cố giáo sư Phan Huy Lê, tổng kết những kiến thức sâu sắc về quá trình hình thành và phát triển của vùng đất Nam Bộ. Sách đi sâu vào các khía cạnh lịch sử, địa lý, kinh tế, xã hội và văn hóa, mang đến một cái nhìn toàn diện và khoa học về một trong những vùng đất quan trọng nhất của Việt Nam.",
    donGia: 350000,
    soLuong: 5,
    conLai: 3,
    namXuatBan: "2021",
    TacGia: "Phan Huy Lê",
    dichGia: "",
    maNXB: "NXB004",
  },
  {
    maSach: "S035",
    tenSach: "Tư duy nhanh và chậm",
    theLoai: "Tâm lý",
    gioiThieu:
      "Nhà tâm lý học đoạt giải Nobel Daniel Kahneman giới thiệu về hai hệ thống tư duy đang vận hành trong não bộ chúng ta: Hệ thống 1 (nhanh, trực giác, cảm tính) và Hệ thống 2 (chậm, logic, lý trí). Cuốn sách giải thích cách hai hệ thống này tương tác và ảnh hưởng đến những quyết định, phán đoán và sai lầm của chúng ta trong cuộc sống. Một cuốn sách thay đổi cách bạn suy nghĩ về chính suy nghĩ của mình.",
    donGia: 195000,
    soLuong: 25,
    conLai: 20,
    namXuatBan: "2023",
    TacGia: "Daniel Kahneman",
    dichGia: "Hà Việt Anh",
    maNXB: "NXB004",
  },
  {
    maSach: "S036",
    tenSach: "Lịch sử Sài Gòn - Chợ Lớn",
    theLoai: "Lịch sử",
    gioiThieu:
      "Học giả Vương Hồng Sển, một người con của Sài Gòn, đã ghi lại những câu chuyện, giai thoại và kiến thức uyên bác của mình về lịch sử hình thành và phát triển của Sài Gòn - Chợ Lớn. Với văn phong độc đáo và khối lượng thông tin đồ sộ, cuốn sách là một kho tàng quý giá về văn hóa, con người và những thăng trầm của vùng đất này.",
    donGia: 145000,
    soLuong: 12,
    conLai: 10,
    namXuatBan: "2022",
    TacGia: "Vương Hồng Sển",
    dichGia: "",
    maNXB: "NXB004",
  },
  {
    maSach: "S037",
    tenSach: "Đắc Nhân Tâm",
    theLoai: "Kỹ năng",
    gioiThieu:
      "Cuốn sách self-help kinh điển nhất mọi thời đại của Dale Carnegie. Tác phẩm đưa ra những nguyên tắc vàng trong nghệ thuật giao tiếp, ứng xử và thu phục lòng người. Từ việc khen ngợi, lắng nghe cho đến cách giải quyết xung đột, những lời khuyên của Carnegie vẫn giữ nguyên giá trị và đã giúp hàng triệu người thành công hơn trong công việc và cuộc sống.",
    donGia: 86000,
    soLuong: 100,
    conLai: 85,
    namXuatBan: "2024",
    TacGia: "Dale Carnegie",
    dichGia: "Nguyễn Hiến Lê",
    maNXB: "NXB004",
  },
  {
    maSach: "S038",
    tenSach: "Quốc gia khởi nghiệp",
    theLoai: "Kinh tế",
    gioiThieu:
      "Cuốn sách đi tìm lời giải cho câu hỏi: Làm thế nào mà Israel, một quốc gia nhỏ bé, non trẻ và luôn bị bao vây bởi thù địch, lại có thể trở thành một cường quốc công nghệ với số lượng công ty khởi nghiệp nhiều hơn bất kỳ quốc gia nào khác? Tác phẩm phân tích sâu sắc về văn hóa, chính sách và tinh thần đã tạo nên sự thần kỳ kinh tế của Israel.",
    donGia: 138000,
    soLuong: 30,
    conLai: 25,
    namXuatBan: "2023",
    TacGia: "Dan Senor",
    dichGia: "Trí Kiên",
    maNXB: "NXB004",
  },
  {
    maSach: "S039",
    tenSach: "Tiếng người trong gió",
    theLoai: "Văn học",
    gioiThieu:
      "Tuyển tập những truyện ngắn đặc sắc của các nhà văn tiêu biểu cho văn học Nam Bộ như Sơn Nam, Bình Nguyên Lộc, Nguyễn Ngọc Tư... Mỗi câu chuyện mang một hương vị riêng, nhưng tất cả đều phản ánh được tâm hồn, tính cách phóng khoáng, nghĩa tình và cuộc sống đầy biến động của con người và vùng đất phương Nam.",
    donGia: 95000,
    soLuong: 8,
    conLai: 8,
    namXuatBan: "2022",
    TacGia: "Nhiều tác giả",
    dichGia: "",
    maNXB: "NXB004",
  },
  {
    maSach: "S040",
    tenSach: "Văn hóa Việt Nam tổng quan",
    theLoai: "Văn hóa",
    gioiThieu:
      "Công trình nghiên cứu của học giả Phan Ngọc, cung cấp một cái nhìn hệ thống và sâu sắc về các đặc trưng, cấu trúc và giá trị của văn hóa Việt Nam. Sách phân tích các yếu tố như ngôn ngữ, tín ngưỡng, phong tục, nghệ thuật... để làm nổi bật bản sắc văn hóa dân tộc trong sự giao thoa với các nền văn hóa khác trong khu vực và trên thế giới.",
    donGia: 160000,
    soLuong: 15,
    conLai: 14,
    namXuatBan: "2021",
    TacGia: "Phan Ngọc",
    dichGia: "",
    maNXB: "NXB004",
  },

  // Phanbook (NXB005) - 10 cuốn (Văn học hiện đại, Nghệ thuật)
  {
    maSach: "S041",
    tenSach: "Kỳ án ánh trăng",
    theLoai: "Trinh thám",
    gioiThieu:
      "Một tiểu thuyết trinh thám ly kỳ của Quỷ Cổ Nữ, một trong những tác giả nổi tiếng của dòng văn học này tại Trung Quốc. Câu chuyện bắt đầu bằng một vụ án mạng bí ẩn xảy ra trong một đêm trăng, kéo theo hàng loạt những sự kiện rùng rợn và những bí mật được chôn giấu từ quá khứ. Tác phẩm kết hợp yếu tố kinh dị và trinh thám, tạo nên một không khí ám ảnh và lôi cuốn.",
    donGia: 125000,
    soLuong: 20,
    conLai: 18,
    namXuatBan: "2023",
    TacGia: "Quỷ Cổ Nữ",
    dichGia: "Lục Hương",
    maNXB: "NXB005",
  },
  {
    maSach: "S042",
    tenSach: "Phía sau nghi can X",
    theLoai: "Trinh thám",
    gioiThieu:
      "Một trong những tác phẩm xuất sắc nhất của Higashino Keigo. Câu chuyện không chỉ là một vụ án thông thường, mà là một cuộc đấu trí căng thẳng giữa một thiên tài toán học và một nhà vật lý học lỗi lạc. Để bảo vệ người phụ nữ mình yêu, nghi can X đã tạo ra một bằng chứng ngoại phạm hoàn hảo. Tác phẩm là sự kết hợp tuyệt vời giữa trinh thám logic và một câu chuyện tình yêu đầy cảm động và bi kịch.",
    donGia: 110000,
    soLuong: 25,
    conLai: 15,
    namXuatBan: "2024",
    TacGia: "Higashino Keigo",
    dichGia: "Lương Việt Dũng",
    maNXB: "NXB005",
  },
  {
    maSach: "S043",
    tenSach: "Nỗi buồn chiến tranh",
    theLoai: "Văn học",
    gioiThieu:
      "Một tác phẩm văn học Việt Nam gây tiếng vang lớn trên thế giới. Bảo Ninh đã viết về chiến tranh từ góc nhìn của một người lính trở về, với những ký ức rời rạc, những ám ảnh kinh hoàng và nỗi buồn sâu sắc về sự mất mát của cả một thế hệ. 'Nỗi buồn chiến tranh' không phải là một bản anh hùng ca, mà là một lời ai điếu chân thực và đau đớn cho những nạn nhân của chiến tranh.",
    donGia: 140000,
    soLuong: 15,
    conLai: 12,
    namXuatBan: "2022",
    TacGia: "Bảo Ninh",
    dichGia: "",
    maNXB: "NXB005",
  },
  {
    maSach: "S044",
    tenSach: "Bạch Dạ Hành",
    theLoai: "Trinh thám",
    gioiThieu:
      "Một tiểu thuyết đồ sộ và phức tạp của Higashino Keigo. Câu chuyện theo chân cuộc đời của Ryoji và Yukiho trong suốt 20 năm, sau khi một vụ án mạng xảy ra. Họ dường như không liên quan đến nhau, nhưng luôn có một sợi dây vô hình kết nối họ qua hàng loạt những bi kịch và tội ác. 'Bạch Dạ Hành' là một bức tranh tăm tối về tâm hồn con người và cái giá phải trả cho những lỗi lầm trong quá khứ.",
    donGia: 175000,
    soLuong: 20,
    conLai: 10,
    namXuatBan: "2023",
    TacGia: "Higashino Keigo",
    dichGia: "Diệu Thúy",
    maNXB: "NXB005",
  },
  {
    maSach: "S045",
    tenSach: "Lạc lối ở Bắc Kinh",
    theLoai: "Văn học",
    gioiThieu:
      "Tuyển tập truyện ngắn của các nhà văn trẻ Trung Quốc, vẽ nên một bức tranh đa dạng về cuộc sống của thế hệ trẻ ở Bắc Kinh hiện đại. Họ phải đối mặt với áp lực công việc, sự cô đơn, những mối quan hệ phức tạp và cảm giác hoang mang, lạc lối giữa một đô thị khổng lồ. Tác phẩm phản ánh những vấn đề xã hội và tâm lý của một thế hệ đang trong quá trình chuyển đổi.",
    donGia: 98000,
    soLuong: 10,
    conLai: 9,
    namXuatBan: "2023",
    TacGia: "Nhiều tác giả",
    dichGia: "Lê Huy",
    maNXB: "NXB005",
  },
  {
    maSach: "S046",
    tenSach: "Nghệ thuật tư duy rành mạch",
    theLoai: "Tâm lý",
    gioiThieu:
      "Rolf Dobelli đã tổng hợp 99 lỗi tư duy phổ biến mà con người thường mắc phải trong cuộc sống hàng ngày, từ hiệu ứng mỏ neo, thiên kiến xác nhận cho đến ngụy biện chi phí chìm. Mỗi lỗi tư duy được giải thích một cách ngắn gọn, súc tích với những ví dụ thực tế. Cuốn sách là một công cụ hữu ích giúp bạn nhận diện và tránh những cạm bẫy của tư duy, từ đó đưa ra những quyết định sáng suốt hơn.",
    donGia: 155000,
    soLuong: 30,
    conLai: 22,
    namXuatBan: "2024",
    TacGia: "Rolf Dobelli",
    dichGia: "Tú Anh",
    maNXB: "NXB005",
  },
  {
    maSach: "S047",
    tenSach: "Kể chuyện hội họa",
    theLoai: "Nghệ thuật",
    gioiThieu:
      "Họa sĩ, nhà nghiên cứu mỹ thuật Phan Cẩm Thượng dẫn dắt độc giả vào thế giới hội họa qua những câu chuyện thú vị và kiến thức uyên bác. Sách không chỉ giới thiệu về lịch sử hội họa Việt Nam và thế giới, mà còn phân tích các tác phẩm, trường phái và nghệ sĩ tiêu biểu. Với lối kể chuyện hấp dẫn, cuốn sách giúp nghệ thuật trở nên gần gũi và dễ hiểu hơn với công chúng.",
    donGia: 220000,
    soLuong: 5,
    conLai: 2,
    namXuatBan: "2022",
    TacGia: "Phan Cẩm Thượng",
    dichGia: "",
    maNXB: "NXB005",
  },
  {
    maSach: "S048",
    tenSach: "Người lạ",
    theLoai: "Văn học",
    gioiThieu:
      "Tác phẩm mở đầu cho triết học phi lý của Albert Camus. Nhân vật chính, Meursault, là một người đàn ông sống thờ ơ và xa lạ với mọi quy tắc, tình cảm và kỳ vọng của xã hội. Anh ta không khóc trong đám tang mẹ và gây ra một án mạng vì ánh nắng mặt trời. 'Người lạ' đặt ra những câu hỏi nhức nhối về sự tồn tại, tự do và ý nghĩa của cuộc sống trong một vũ trụ phi lý.",
    donGia: 89000,
    soLuong: 20,
    conLai: 20,
    namXuatBan: "2023",
    TacGia: "Albert Camus",
    dichGia: "Lê Thanh Hoàng Dân",
    maNXB: "NXB005",
  },
  {
    maSach: "S049",
    tenSach: "Sự im lặng của bầy cừu",
    theLoai: "Kinh dị",
    gioiThieu:
      "Một tiểu thuyết kinh dị tâm lý kinh điển. Nữ thực tập sinh FBI Clarice Starling được giao nhiệm vụ phỏng vấn bác sĩ Hannibal Lecter, một kẻ ăn thịt người thông minh và tàn bạo, để lấy thông tin về một tên giết người hàng loạt khác. Cuộc đấu trí căng thẳng và đầy ám ảnh giữa Clarice và Hannibal đã tạo nên một trong những câu chuyện rùng rợn và hấp dẫn nhất của văn học hiện đại.",
    donGia: 135000,
    soLuong: 15,
    conLai: 14,
    namXuatBan: "2024",
    TacGia: "Thomas Harris",
    dichGia: "Phạm Hồng Anh",
    maNXB: "NXB005",
  },
  {
    maSach: "S050",
    tenSach: "Đi tìm thời gian đã mất",
    theLoai: "Kinh điển",
    gioiThieu:
      "Bộ tiểu thuyết đồ sộ được coi là một trong những tác phẩm vĩ đại nhất của thế kỷ 20. Marcel Proust đã thực hiện một cuộc thám hiểm sâu vào ký ức, thời gian và nội tâm con người. Thông qua dòng ý thức của nhân vật, tác phẩm tái hiện lại xã hội thượng lưu Pháp cuối thế kỷ 19, đồng thời phân tích một cách tinh vi về tình yêu, nghệ thuật và bản chất của ký ức. Đây là một thử thách nhưng cũng là một trải nghiệm văn học đỉnh cao.",
    donGia: 280000,
    soLuong: 10,
    conLai: 7,
    namXuatBan: "2021",
    TacGia: "Marcel Proust",
    dichGia: "Lê Hồng Sâm",
    maNXB: "NXB005",
  },
]);
